// Code generated by entc, DO NOT EDIT.

package playlist

const (
	// Label holds the string label denoting the playlist type in the database.
	Label = "playlist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgePlaylistVideos holds the string denoting the playlist_videos edge name in mutations.
	EdgePlaylistVideos = "playlist_videos"

	// Table holds the table name of the playlist in the database.
	Table = "playlists"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "playlists"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// PlaylistVideosTable is the table the holds the playlist_videos relation/edge.
	PlaylistVideosTable = "playlist_videos"
	// PlaylistVideosInverseTable is the table name for the Playlist_Video entity.
	// It exists in this package in order to avoid circular dependency with the "playlist_video" package.
	PlaylistVideosInverseTable = "playlist_videos"
	// PlaylistVideosColumn is the table column denoting the playlist_videos relation/edge.
	PlaylistVideosColumn = "playlist_id"
)

// Columns holds all SQL columns for playlist fields.
var Columns = []string{
	FieldID,
	FieldTitle,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Playlist type.
var ForeignKeys = []string{
	"owner_id",
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)
