// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6001186/Contagions/ent/bloodtype"
	"github.com/B6001186/Contagions/ent/patient"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BloodtypeCreate is the builder for creating a Bloodtype entity.
type BloodtypeCreate struct {
	config
	mutation *BloodtypeMutation
	hooks    []Hook
}

// SetBloodtypeName sets the BloodtypeName field.
func (bc *BloodtypeCreate) SetBloodtypeName(s string) *BloodtypeCreate {
	bc.mutation.SetBloodtypeName(s)
	return bc
}

// AddPatientIDs adds the patient edge to Patient by ids.
func (bc *BloodtypeCreate) AddPatientIDs(ids ...int) *BloodtypeCreate {
	bc.mutation.AddPatientIDs(ids...)
	return bc
}

// AddPatient adds the patient edges to Patient.
func (bc *BloodtypeCreate) AddPatient(p ...*Patient) *BloodtypeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return bc.AddPatientIDs(ids...)
}

// Mutation returns the BloodtypeMutation object of the builder.
func (bc *BloodtypeCreate) Mutation() *BloodtypeMutation {
	return bc.mutation
}

// Save creates the Bloodtype in the database.
func (bc *BloodtypeCreate) Save(ctx context.Context) (*Bloodtype, error) {
	if _, ok := bc.mutation.BloodtypeName(); !ok {
		return nil, &ValidationError{Name: "BloodtypeName", err: errors.New("ent: missing required field \"BloodtypeName\"")}
	}
	var (
		err  error
		node *Bloodtype
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BloodtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BloodtypeCreate) SaveX(ctx context.Context) *Bloodtype {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BloodtypeCreate) sqlSave(ctx context.Context) (*Bloodtype, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BloodtypeCreate) createSpec() (*Bloodtype, *sqlgraph.CreateSpec) {
	var (
		b     = &Bloodtype{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bloodtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bloodtype.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.BloodtypeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bloodtype.FieldBloodtypeName,
		})
		b.BloodtypeName = value
	}
	if nodes := bc.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bloodtype.PatientTable,
			Columns: []string{bloodtype.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
