// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/B6001186/Contagions/ent/diseasetype"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Diseasetype is the model entity for the Diseasetype schema.
type Diseasetype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DiseaseTypeName holds the value of the "DiseaseTypeName" field.
	DiseaseTypeName string `json:"DiseaseTypeName,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiseasetypeQuery when eager-loading is set.
	Edges DiseasetypeEdges `json:"edges"`
}

// DiseasetypeEdges holds the relations/edges for other nodes in the graph.
type DiseasetypeEdges struct {
	// Disease holds the value of the disease edge.
	Disease []*Disease
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DiseaseOrErr returns the Disease value or an error if the edge
// was not loaded in eager-loading.
func (e DiseasetypeEdges) DiseaseOrErr() ([]*Disease, error) {
	if e.loadedTypes[0] {
		return e.Disease, nil
	}
	return nil, &NotLoadedError{edge: "disease"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Diseasetype) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // DiseaseTypeName
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Diseasetype fields.
func (d *Diseasetype) assignValues(values ...interface{}) error {
	if m, n := len(values), len(diseasetype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field DiseaseTypeName", values[0])
	} else if value.Valid {
		d.DiseaseTypeName = value.String
	}
	return nil
}

// QueryDisease queries the disease edge of the Diseasetype.
func (d *Diseasetype) QueryDisease() *DiseaseQuery {
	return (&DiseasetypeClient{config: d.config}).QueryDisease(d)
}

// Update returns a builder for updating this Diseasetype.
// Note that, you need to call Diseasetype.Unwrap() before calling this method, if this Diseasetype
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Diseasetype) Update() *DiseasetypeUpdateOne {
	return (&DiseasetypeClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Diseasetype) Unwrap() *Diseasetype {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Diseasetype is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Diseasetype) String() string {
	var builder strings.Builder
	builder.WriteString("Diseasetype(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", DiseaseTypeName=")
	builder.WriteString(d.DiseaseTypeName)
	builder.WriteByte(')')
	return builder.String()
}

// Diseasetypes is a parsable slice of Diseasetype.
type Diseasetypes []*Diseasetype

func (d Diseasetypes) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
