// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6001186/Contagions/ent/disease"
	"github.com/B6001186/Contagions/ent/diseasetype"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DiseasetypeCreate is the builder for creating a Diseasetype entity.
type DiseasetypeCreate struct {
	config
	mutation *DiseasetypeMutation
	hooks    []Hook
}

// SetDiseaseTypeName sets the DiseaseTypeName field.
func (dc *DiseasetypeCreate) SetDiseaseTypeName(s string) *DiseasetypeCreate {
	dc.mutation.SetDiseaseTypeName(s)
	return dc
}

// AddDiseaseIDs adds the disease edge to Disease by ids.
func (dc *DiseasetypeCreate) AddDiseaseIDs(ids ...int) *DiseasetypeCreate {
	dc.mutation.AddDiseaseIDs(ids...)
	return dc
}

// AddDisease adds the disease edges to Disease.
func (dc *DiseasetypeCreate) AddDisease(d ...*Disease) *DiseasetypeCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dc.AddDiseaseIDs(ids...)
}

// Mutation returns the DiseasetypeMutation object of the builder.
func (dc *DiseasetypeCreate) Mutation() *DiseasetypeMutation {
	return dc.mutation
}

// Save creates the Diseasetype in the database.
func (dc *DiseasetypeCreate) Save(ctx context.Context) (*Diseasetype, error) {
	if _, ok := dc.mutation.DiseaseTypeName(); !ok {
		return nil, &ValidationError{Name: "DiseaseTypeName", err: errors.New("ent: missing required field \"DiseaseTypeName\"")}
	}
	var (
		err  error
		node *Diseasetype
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiseasetypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DiseasetypeCreate) SaveX(ctx context.Context) *Diseasetype {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DiseasetypeCreate) sqlSave(ctx context.Context) (*Diseasetype, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DiseasetypeCreate) createSpec() (*Diseasetype, *sqlgraph.CreateSpec) {
	var (
		d     = &Diseasetype{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: diseasetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: diseasetype.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.DiseaseTypeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: diseasetype.FieldDiseaseTypeName,
		})
		d.DiseaseTypeName = value
	}
	if nodes := dc.mutation.DiseaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diseasetype.DiseaseTable,
			Columns: []string{diseasetype.DiseaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
