// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/B6001186/Contagions/ent/diagnosis"
	"github.com/B6001186/Contagions/ent/patient"
	"github.com/B6001186/Contagions/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	diagnosisFields := schema.Diagnosis{}.Fields()
	_ = diagnosisFields
	// diagnosisDescDiagnosticMessages is the schema descriptor for DiagnosticMessages field.
	diagnosisDescDiagnosticMessages := diagnosisFields[0].Descriptor()
	// diagnosis.DiagnosticMessagesValidator is a validator for the "DiagnosticMessages" field. It is called by the builders before save.
	diagnosis.DiagnosticMessagesValidator = func() func(string) error {
		validators := diagnosisDescDiagnosticMessages.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_DiagnosticMessages string) error {
			for _, fn := range fns {
				if err := fn(_DiagnosticMessages); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// diagnosisDescSurveillancePeriod is the schema descriptor for SurveillancePeriod field.
	diagnosisDescSurveillancePeriod := diagnosisFields[1].Descriptor()
	// diagnosis.SurveillancePeriodValidator is a validator for the "SurveillancePeriod" field. It is called by the builders before save.
	diagnosis.SurveillancePeriodValidator = func() func(string) error {
		validators := diagnosisDescSurveillancePeriod.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_SurveillancePeriod string) error {
			for _, fn := range fns {
				if err := fn(_SurveillancePeriod); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// diagnosisDescTreatment is the schema descriptor for Treatment field.
	diagnosisDescTreatment := diagnosisFields[2].Descriptor()
	// diagnosis.TreatmentValidator is a validator for the "Treatment" field. It is called by the builders before save.
	diagnosis.TreatmentValidator = func() func(string) error {
		validators := diagnosisDescTreatment.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Treatment string) error {
			for _, fn := range fns {
				if err := fn(_Treatment); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescIdcard is the schema descriptor for Idcard field.
	patientDescIdcard := patientFields[0].Descriptor()
	// patient.IdcardValidator is a validator for the "Idcard" field. It is called by the builders before save.
	patient.IdcardValidator = func() func(string) error {
		validators := patientDescIdcard.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_Idcard string) error {
			for _, fn := range fns {
				if err := fn(_Idcard); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// patientDescPatientName is the schema descriptor for PatientName field.
	patientDescPatientName := patientFields[1].Descriptor()
	// patient.PatientNameValidator is a validator for the "PatientName" field. It is called by the builders before save.
	patient.PatientNameValidator = patientDescPatientName.Validators[0].(func(string) error)
	// patientDescAddress is the schema descriptor for Address field.
	patientDescAddress := patientFields[2].Descriptor()
	// patient.AddressValidator is a validator for the "Address" field. It is called by the builders before save.
	patient.AddressValidator = patientDescAddress.Validators[0].(func(string) error)
	// patientDescCongenital is the schema descriptor for Congenital field.
	patientDescCongenital := patientFields[3].Descriptor()
	// patient.CongenitalValidator is a validator for the "Congenital" field. It is called by the builders before save.
	patient.CongenitalValidator = patientDescCongenital.Validators[0].(func(string) error)
	// patientDescAllergic is the schema descriptor for Allergic field.
	patientDescAllergic := patientFields[4].Descriptor()
	// patient.AllergicValidator is a validator for the "Allergic" field. It is called by the builders before save.
	patient.AllergicValidator = patientDescAllergic.Validators[0].(func(string) error)
}
