// Code generated by entc, DO NOT EDIT.

package video

const (
	// Label holds the string label denoting the video type in the database.
	Label = "video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgePlaylistVideos holds the string denoting the playlist_videos edge name in mutations.
	EdgePlaylistVideos = "playlist_videos"

	// Table holds the table name of the video in the database.
	Table = "videos"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "videos"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// PlaylistVideosTable is the table the holds the playlist_videos relation/edge.
	PlaylistVideosTable = "playlist_videos"
	// PlaylistVideosInverseTable is the table name for the Playlist_Video entity.
	// It exists in this package in order to avoid circular dependency with the "playlist_video" package.
	PlaylistVideosInverseTable = "playlist_videos"
	// PlaylistVideosColumn is the table column denoting the playlist_videos relation/edge.
	PlaylistVideosColumn = "video_id"
)

// Columns holds all SQL columns for video fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldURL,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Video type.
var ForeignKeys = []string{
	"owner_id",
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
)
