// Code generated by entc, DO NOT EDIT.

package severity

import (
	"github.com/B6001186/Contagions/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// SeverityName applies equality check predicate on the "SeverityName" field. It's identical to SeverityNameEQ.
func SeverityName(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeverityName), v))
	})
}

// SeverityNameEQ applies the EQ predicate on the "SeverityName" field.
func SeverityNameEQ(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeverityName), v))
	})
}

// SeverityNameNEQ applies the NEQ predicate on the "SeverityName" field.
func SeverityNameNEQ(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeverityName), v))
	})
}

// SeverityNameIn applies the In predicate on the "SeverityName" field.
func SeverityNameIn(vs ...string) predicate.Severity {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Severity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeverityName), v...))
	})
}

// SeverityNameNotIn applies the NotIn predicate on the "SeverityName" field.
func SeverityNameNotIn(vs ...string) predicate.Severity {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Severity(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeverityName), v...))
	})
}

// SeverityNameGT applies the GT predicate on the "SeverityName" field.
func SeverityNameGT(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSeverityName), v))
	})
}

// SeverityNameGTE applies the GTE predicate on the "SeverityName" field.
func SeverityNameGTE(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSeverityName), v))
	})
}

// SeverityNameLT applies the LT predicate on the "SeverityName" field.
func SeverityNameLT(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSeverityName), v))
	})
}

// SeverityNameLTE applies the LTE predicate on the "SeverityName" field.
func SeverityNameLTE(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSeverityName), v))
	})
}

// SeverityNameContains applies the Contains predicate on the "SeverityName" field.
func SeverityNameContains(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSeverityName), v))
	})
}

// SeverityNameHasPrefix applies the HasPrefix predicate on the "SeverityName" field.
func SeverityNameHasPrefix(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSeverityName), v))
	})
}

// SeverityNameHasSuffix applies the HasSuffix predicate on the "SeverityName" field.
func SeverityNameHasSuffix(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSeverityName), v))
	})
}

// SeverityNameEqualFold applies the EqualFold predicate on the "SeverityName" field.
func SeverityNameEqualFold(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSeverityName), v))
	})
}

// SeverityNameContainsFold applies the ContainsFold predicate on the "SeverityName" field.
func SeverityNameContainsFold(v string) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSeverityName), v))
	})
}

// HasDisease applies the HasEdge predicate on the "disease" edge.
func HasDisease() predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DiseaseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DiseaseTable, DiseaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiseaseWith applies the HasEdge predicate on the "disease" edge with a given conditions (other predicates).
func HasDiseaseWith(preds ...predicate.Disease) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DiseaseInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DiseaseTable, DiseaseColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Severity) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Severity) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Severity) predicate.Severity {
	return predicate.Severity(func(s *sql.Selector) {
		p(s.Not())
	})
}
