/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPlaylistVideo
 */
export interface ControllersPlaylistVideo {
    /**
     * 
     * @type {string}
     * @memberof ControllersPlaylistVideo
     */
    added?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPlaylistVideo
     */
    playlist?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPlaylistVideo
     */
    resolution?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPlaylistVideo
     */
    video?: number;
}

export function ControllersPlaylistVideoFromJSON(json: any): ControllersPlaylistVideo {
    return ControllersPlaylistVideoFromJSONTyped(json, false);
}

export function ControllersPlaylistVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPlaylistVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'playlist': !exists(json, 'playlist') ? undefined : json['playlist'],
        'resolution': !exists(json, 'resolution') ? undefined : json['resolution'],
        'video': !exists(json, 'video') ? undefined : json['video'],
    };
}

export function ControllersPlaylistVideoToJSON(value?: ControllersPlaylistVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'playlist': value.playlist,
        'resolution': value.resolution,
        'video': value.video,
    };
}


