/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntResolutionEdges,
    EntResolutionEdgesFromJSON,
    EntResolutionEdgesFromJSONTyped,
    EntResolutionEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntResolution
 */
export interface EntResolution {
    /**
     * 
     * @type {EntResolutionEdges}
     * @memberof EntResolution
     */
    edges?: EntResolutionEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntResolution
     */
    id?: number;
    /**
     * Value holds the value of the "value" field.
     * @type {number}
     * @memberof EntResolution
     */
    value?: number;
}

export function EntResolutionFromJSON(json: any): EntResolution {
    return EntResolutionFromJSONTyped(json, false);
}

export function EntResolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntResolution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntResolutionEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function EntResolutionToJSON(value?: EntResolution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntResolutionEdgesToJSON(value.edges),
        'id': value.id,
        'value': value.value,
    };
}


