/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrug,
    EntDrugFromJSON,
    EntDrugFromJSONTyped,
    EntDrugToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDrugTypeEdges
 */
export interface EntDrugTypeEdges {
    /**
     * Drug holds the value of the drug edge.
     * @type {Array<EntDrug>}
     * @memberof EntDrugTypeEdges
     */
    drug?: Array<EntDrug>;
}

export function EntDrugTypeEdgesFromJSON(json: any): EntDrugTypeEdges {
    return EntDrugTypeEdgesFromJSONTyped(json, false);
}

export function EntDrugTypeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDrugTypeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drug': !exists(json, 'drug') ? undefined : ((json['drug'] as Array<any>).map(EntDrugFromJSON)),
    };
}

export function EntDrugTypeEdgesToJSON(value?: EntDrugTypeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drug': value.drug === undefined ? undefined : ((value.drug as Array<any>).map(EntDrugToJSON)),
    };
}


