// Code generated by entc, DO NOT EDIT.

package playlist_video

const (
	// Label holds the string label denoting the playlist_video type in the database.
	Label = "playlist_video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// EdgePlaylist holds the string denoting the playlist edge name in mutations.
	EdgePlaylist = "playlist"
	// EdgeVideo holds the string denoting the video edge name in mutations.
	EdgeVideo = "video"
	// EdgeResolution holds the string denoting the resolution edge name in mutations.
	EdgeResolution = "resolution"

	// Table holds the table name of the playlist_video in the database.
	Table = "playlist_videos"
	// PlaylistTable is the table the holds the playlist relation/edge.
	PlaylistTable = "playlist_videos"
	// PlaylistInverseTable is the table name for the Playlist entity.
	// It exists in this package in order to avoid circular dependency with the "playlist" package.
	PlaylistInverseTable = "playlists"
	// PlaylistColumn is the table column denoting the playlist relation/edge.
	PlaylistColumn = "playlist_id"
	// VideoTable is the table the holds the video relation/edge.
	VideoTable = "playlist_videos"
	// VideoInverseTable is the table name for the Video entity.
	// It exists in this package in order to avoid circular dependency with the "video" package.
	VideoInverseTable = "videos"
	// VideoColumn is the table column denoting the video relation/edge.
	VideoColumn = "video_id"
	// ResolutionTable is the table the holds the resolution relation/edge.
	ResolutionTable = "playlist_videos"
	// ResolutionInverseTable is the table name for the Resolution entity.
	// It exists in this package in order to avoid circular dependency with the "resolution" package.
	ResolutionInverseTable = "resolutions"
	// ResolutionColumn is the table column denoting the resolution relation/edge.
	ResolutionColumn = "resolution_id"
)

// Columns holds all SQL columns for playlist_video fields.
var Columns = []string{
	FieldID,
	FieldAddedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Playlist_Video type.
var ForeignKeys = []string{
	"playlist_id",
	"resolution_id",
	"video_id",
}
